package com.boole.common.domain;
// Generated Nov 10, 2015 11:08:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Genre generated by hbm2java
 */
@Entity
@Table(name = "genres", schema = "public")
public class Genre extends AbstractBaseEntity {

    private String name;


    @ManyToMany(mappedBy = "genres")
    private Set<Movie> movies = new HashSet<>(0);

    public Genre() {
    }

    public Genre(Long id, LocalDateTime createdAt, LocalDateTime updatedAt) {
        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }

    public Genre(Long id, String name, LocalDateTime createdAt, LocalDateTime updatedAt) {
        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        this.name = name;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

}
