package com.boole.common.domain;
// Generated Nov 10, 2015 11:08:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "movies", schema = "public")
public class Movie extends AbstractBaseEntity {

    private String name;
    private String synopsis;
    private String country;
    private Integer year;
    private Double review;
    private String rating;
    private Integer runtime;
    private String language;
    private ZonedDateTime releaseDate;
    private Set<Role> roles = new HashSet<>(0);
    private Set<Genre> genres = new HashSet<>(0);

    public Movie() {
    }

    public Movie(Long id, ZonedDateTime createdAt, ZonedDateTime updatedAt) {
        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }

    public Movie(Long id, String name, String synopsis, ZonedDateTime createdAt, ZonedDateTime updatedAt, String country, Integer year,
                 Double review, String rating, Integer runtime, String language, ZonedDateTime releaseDate, Set<Role> roles) {
        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        this.name = name;
        this.synopsis = synopsis;
        this.country = country;
        this.year = year;
        this.review = review;
        this.rating = rating;
        this.runtime = runtime;
        this.language = language;
        this.releaseDate = releaseDate;
        this.roles = roles;
    }

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "genres_movies",
            schema = "public",
            joinColumns = @JoinColumn(name = "movie_id"),
            inverseJoinColumns = @JoinColumn(name = "genre_id"))
    public Set<Genre> getGenres() {
        return genres;
    }

    public void setGenres(Set<Genre> genres) {
        this.genres = genres;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "synopsis")
    public String getSynopsis() {
        return this.synopsis;
    }

    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis;
    }

    @Column(name = "country")
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Column(name = "year")
    public Integer getYear() {
        return this.year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    @Column(name = "review", precision = 17, scale = 17)
    public Double getReview() {
        return this.review;
    }

    public void setReview(Double review) {
        this.review = review;
    }

    @Column(name = "rating")
    public String getRating() {
        return this.rating;
    }

    public void setRating(String rating) {
        this.rating = rating;
    }

    @Column(name = "runtime")
    public Integer getRuntime() {
        return this.runtime;
    }

    public void setRuntime(Integer runtime) {
        this.runtime = runtime;
    }

    @Column(name = "language")
    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }


    @Column(name = "release_date", length = 13)
    public ZonedDateTime getReleaseDate() {
        return this.releaseDate;
    }

    public void setReleaseDate(ZonedDateTime releaseDate) {
        this.releaseDate = releaseDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "movie")
    public Set<Role> getRoles() {
        return this.roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

}
