package com.boole.common.domain;
// Generated Nov 10, 2015 11:08:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.time.LocalDateTime;
import java.time.ZonedDateTime;

/**
 * Role generated by hbm2java
 */
@Entity
@Table(name = "roles", schema = "public")
public class Role extends AbstractBaseEntity {

    private Crew crew;
    private Movie movie;
    private String job;

    public Role() {
    }

    public Role(Long id, ZonedDateTime createdAt, ZonedDateTime updatedAt) {
        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
    }

    public Role(Long id, Crew crew, Movie movie, String job, ZonedDateTime createdAt, ZonedDateTime updatedAt) {
        setId(id);
        setCreatedAt(createdAt);
        setUpdatedAt(updatedAt);
        this.crew = crew;
        this.movie = movie;
        this.job = job;
    }

    //always fetch the person associated with this role.
    @ManyToOne(fetch = FetchType.EAGER)
    @JoinColumn(name = "crew_id")
    public Crew getCrew() {
        return this.crew;
    }

    public void setCrew(Crew crew) {
        this.crew = crew;
    }

    @ManyToOne(fetch = FetchType.LAZY)
    @JoinColumn(name = "movie_id")
    public Movie getMovie() {
        return this.movie;
    }

    public void setMovie(Movie movie) {
        this.movie = movie;
    }

    @Column(name = "job")
    public String getJob() {
        return this.job;
    }

    public void setJob(String job) {
        this.job = job;
    }


    @Override
    public String toString() {
        return "Role{" +
                "id=" + getId() +
                ", job='" + job + '\'' +
                ", createdAt=" + getCreatedAt() +
                ", updatedAt=" + getUpdatedAt() +
                '}';
    }
}
