package com.sakila.web.domain;
// Generated Nov 10, 2015 11:08:57 PM by Hibernate Tools 4.3.1.Final

import javax.persistence.*;
import java.time.LocalDateTime;
import java.util.HashSet;
import java.util.Set;

/**
 * Movie generated by hbm2java
 */
@Entity
@Table(name = "movies", schema = "public")
public class Movie implements java.io.Serializable {

    private Long id;
    private String name;
    private String synopsis;
    private LocalDateTime createdAt;
    private LocalDateTime updatedAt;
    private String country;
    private Integer year;
    private Double review;
    private String rating;
    private Integer runtime;
    private String language;
    private LocalDateTime releaseDate;
    private Set<Role> roles = new HashSet<>(0);
    private Set<Genre> genres = new HashSet<>(0);

    //@ManyToMany(mappedBy="movies")
    @ManyToMany
    @JoinTable(name = "genres_movies",
            schema = "public",
            joinColumns = @JoinColumn(name = "movie_id"),
            inverseJoinColumns = @JoinColumn(name = "genre_id"))
    public Set<Genre> getGenres() {
        return genres;
    }

    public void setGenres(Set<Genre> genres) {
        this.genres = genres;
    }

    public Movie() {
    }

    public Movie(Long id, LocalDateTime createdAt, LocalDateTime updatedAt) {
        this.id = id;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
    }

    public Movie(Long id, String name, String synopsis, LocalDateTime createdAt, LocalDateTime updatedAt, String country, Integer year,
                 Double review, String rating, Integer runtime, String language, LocalDateTime releaseDate, Set<Role> roles) {
        this.id = id;
        this.name = name;
        this.synopsis = synopsis;
        this.createdAt = createdAt;
        this.updatedAt = updatedAt;
        this.country = country;
        this.year = year;
        this.review = review;
        this.rating = rating;
        this.runtime = runtime;
        this.language = language;
        this.releaseDate = releaseDate;
        this.roles = roles;
    }

    @Id

    @Column(name = "id", unique = true, nullable = false)
    public Long getId() {
        return this.id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    @Column(name = "name")
    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Column(name = "synopsis")
    public String getSynopsis() {
        return this.synopsis;
    }

    public void setSynopsis(String synopsis) {
        this.synopsis = synopsis;
    }

    //@Temporal(TemporalType.TIMESTAMP)
    @Column(name = "created_at", nullable = false, length = 29)
    public LocalDateTime getCreatedAt() {
        return this.createdAt;
    }

    public void setCreatedAt(LocalDateTime createdAt) {
        this.createdAt = createdAt;
    }

    //@Temporal(TemporalType.TIMESTAMP)
    @Column(name = "updated_at", nullable = false, length = 29)
    public LocalDateTime getUpdatedAt() {
        return this.updatedAt;
    }

    public void setUpdatedAt(LocalDateTime updatedAt) {
        this.updatedAt = updatedAt;
    }

    @Column(name = "country")
    public String getCountry() {
        return this.country;
    }

    public void setCountry(String country) {
        this.country = country;
    }

    @Column(name = "year")
    public Integer getYear() {
        return this.year;
    }

    public void setYear(Integer year) {
        this.year = year;
    }

    @Column(name = "review", precision = 17, scale = 17)
    public Double getReview() {
        return this.review;
    }

    public void setReview(Double review) {
        this.review = review;
    }

    @Column(name = "rating")
    public String getRating() {
        return this.rating;
    }

    public void setRating(String rating) {
        this.rating = rating;
    }

    @Column(name = "runtime")
    public Integer getRuntime() {
        return this.runtime;
    }

    public void setRuntime(Integer runtime) {
        this.runtime = runtime;
    }

    @Column(name = "language")
    public String getLanguage() {
        return this.language;
    }

    public void setLanguage(String language) {
        this.language = language;
    }

    //@Temporal(TemporalType.DATE)
    @Column(name = "release_date", length = 13)
    public LocalDateTime getReleaseDate() {
        return this.releaseDate;
    }

    public void setReleaseDate(LocalDateTime releaseDate) {
        this.releaseDate = releaseDate;
    }

    @OneToMany(fetch = FetchType.LAZY, mappedBy = "movie")
    public Set<Role> getRoles() {
        return this.roles;
    }

    public void setRoles(Set<Role> roles) {
        this.roles = roles;
    }

}
